services:
  scheduled-runtime:
    restart: "no"
    environment:
      BOT_MODE: normal
      MYSQL_PERSISTENCE_ENABLED: "true"

  runtime:
    restart: "no"
    environment:
      BOT_MODE: normal
      MYSQL_PERSISTENCE_ENABLED: "true"
